export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hdGhldXMgVGVpeGVpcmEiLCJlbWFpbCI6Im1hdGhldXNAdGVzdGUuY29tIiwiaWF0IjoxNzIzNzQzNzk3LCJleHAiOjE3MjQzNDg1OTcsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIxIn0.FwaFV2g34KojfLlA0B78mOQckPd2_BAHvebwbTm4EhY';
